version: '3.8'

services:
  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_USER: zenycero
      POSTGRES_PASSWORD: zenycero
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: zenycero
      MONGO_INITDB_ROOT_PASSWORD: zenycero
      MONGO_INITDB_DATABASE: mongodb

  neo4j:
    image: neo4j:5.6.0
    container_name: neo4j
    environment:
      NEO4J_AUTH: "neo4j/zenycero"  # Set your desired username and password here
    ports:
      - "7474:7474"  # HTTP interface
      - "7687:7687"  # Bolt interface
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
    networks:
      - neo4j-network
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
  neo4j-network:
    driver: bridge

volumes:
  postgres:
    driver: local
  mongo-data:
    driver: local
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
