server:
  port: 8080
spring:
  profiles:
    active: test
  application:
    name: post-service
  data:
    mongodb:
      username: zenycero
      password: zenycero
      authentication-database: admin
      database: mongodb
      host: localhost
      port: 27017

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/